# frontend/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Copy package.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Start the development server
CMD ["npm", "start"]
