services:
  - type: web
    name: asset-anchor-api
    runtime: python
    plan: standard
    region: oregon
    repo: https://github.com/mjoyner1029/Property.git
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    preDeployCommand: bash ../scripts/run_migrations.sh
    startCommand: gunicorn "src.app:create_app()" -w 3 -k gevent -b 0.0.0.0:10000 --timeout 120 --max-requests 2000 --max-requests-jitter 200
    healthCheckPath: /healthz
    healthCheckTimeout: 10
    healthCheckInterval: 30
    dependsOn:
      - name: asset-anchor-redis
      - name: asset-anchor-db
    envVars:
      - key: APP_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"

      # ==== REQUIRED SECRETS ====
      - key: SECRET_KEY
        value: "B9gnyxN7PBmS3cdOhX-uroVQeWqL6RX6VgEmpQ_ifIyqNczbXkE9SOcdUl9UTdIU"
      - key: JWT_SECRET_KEY
        value: "xDlY7V-NXV2hoGWGO5cLcuG80FvjGLdRh-IH6Bj30Wa0Ld2MscLjkxvGUTYW9oGCSCd9bdcZcc-4PcaIm1YeOA"

      - key: STRIPE_PUBLIC_KEY
        value: "pk_live_51RviuHRRzCooiyn90jiCw25KJRD4GXb4enFomJc2x0FKLWeChHCPoNwmXT7vaqjc2XcUuyB8Dl04ocoxo8XM0yPp00AJeM52vN"
      - key: STRIPE_SECRET_KEY
        value: "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"
      - key: STRIPE_WEBHOOK_SECRET
        value: "whsec_BZ1BnegM1hKulG4kKiUbGj2tgDNYV7GI"

      - key: EMAIL_API_KEY
        value: "<PASTE_YOUR_POSTMARK_API_KEY>"

      # ==== OPTIONAL (only if using S3 for uploads) ====
      - key: S3_BUCKET
        value: "asset-anchor"
      - key: S3_REGION
        value: "us-west-1"
      - key: AWS_ACCESS_KEY_ID
        value: "AKIAZ2W4LM2UELSWCUCG"
      - key: AWS_SECRET_ACCESS_KEY
        value: "AKIAZ2W4LM2UELSWCUCG"

      # ==== OPTIONAL (monitoring/logging) ====
      - key: SENTRY_DSN
        value: "https://5a77b5fb4326e998df3ae7a2ad62f316@o4509951555731456.ingest.us.sentry.io/4509951683985408"
      - key: REACT_APP_SENTRY_DSN
        value: "https://e3a1bb54c5add061cdced610c0f39f19@o4509951555731456.ingest.us.sentry.io/4509951885312000"
      # ==== CORS / Frontend ====
      - key: CORS_ORIGINS
        value: https://assetanchor.io,https://www.assetanchor.io,https://assetanchor.vercel.app
      - key: CORS_ALLOW_ORIGINS
        value: https://assetanchor.io,https://www.assetanchor.io,https://assetanchor.vercel.app
      - key: FRONTEND_URL
        value: https://assetanchor.vercel.app

      # ==== Misc ====
      - key: EMAIL_PROVIDER
        value: postmark
      - key: EMAIL_FROM
        value: no-reply@assetanchor.io
      - key: LOG_LEVEL
        value: INFO
      - key: CSP_ENFORCE
        value: "true"

      # Redis (rate limiter + Socket.IO)
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: asset-anchor-redis
          property: connectionString
      - key: RATELIMIT_STORAGE_URI
        fromService:
          type: keyvalue
          name: asset-anchor-redis
          property: connectionString
      - key: SOCKETIO_MESSAGE_QUEUE
        fromService:
          type: keyvalue
          name: asset-anchor-redis
          property: connectionString

      # Database URL via env group
      - fromGroup: asset-anchor-db-env

  - type: keyvalue
    name: asset-anchor-redis
    plan: free
    region: oregon
    ipAllowList: []

databases:
  - name: asset-anchor-db
    plan: standard
    region: oregon
    ipAllowList: []

envVarGroups:
  - name: asset-anchor-db-env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asset-anchor-db
          property: connectionString
