services:
  - type: web
    name: asset-anchor-api
    runtime: python
    plan: standard
    region: oregon
    repo: https://github.com/mjoyner1029/Property.git
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements/prod.txt -c requirements/constraints.txt
    # Run migrations before deployment - this happens before the new instance starts serving traffic
    preDeployCommand: bash ../scripts/run_migrations.sh
    
    # Start the application with Gunicorn + gevent for better concurrency
    startCommand: >
      gunicorn -k gevent -w 4 -b 0.0.0.0:$PORT
      wsgi:app --timeout 120
      --max-requests 2000 --max-requests-jitter 200
    
    # Health check for liveness probes - quick check that doesn't depend on DB
    healthCheckPath: /api/health
    healthCheckTimeout: 10
    healthCheckInterval: 30
    dependsOn:
      - name: asset-anchor-redis
      - name: asset-anchor-db
    envVars:
      - key: APP_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: PYTHONUNBUFFERED
        value: "1"

      # ==== REQUIRED SECRETS ====
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

      - key: EMAIL_API_KEY
        sync: false
        # Postmark or other email service API key

      # ==== OPTIONAL (only if using S3 for uploads) ====
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        value: "us-west-1"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false

      # ==== OPTIONAL (monitoring/logging) ====
      - key: SENTRY_DSN
        sync: false
      
      # ==== CORS / Frontend ====
      - key: CORS_ORIGINS
        value: https://assetanchor.io,https://www.assetanchor.io,https://assetanchor.vercel.app
      # - key: CORS_ALLOW_ORIGINS - Removed duplicate CORS configuration
      #   value: https://assetanchor.io,https://www.assetanchor.io,https://assetanchor.vercel.app
      - key: FRONTEND_URL
        value: https://assetanchor.vercel.app

      # ==== Misc ====
      - key: EMAIL_PROVIDER
        value: postmark
      - key: EMAIL_FROM
        value: no-reply@assetanchor.io
      - key: LOG_LEVEL
        value: INFO
      - key: CSP_ENFORCE
        value: "true"

      # ==== Redis (rate limiter + Socket.IO) ====
      # Note: Only needed if using Redis for rate limiting or Socket.IO
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: asset-anchor-redis
          property: connectionString
      - key: RATELIMIT_STORAGE_URI
        fromService:
          type: keyvalue
          name: asset-anchor-redis
          property: connectionString
      - key: SOCKETIO_MESSAGE_QUEUE
        fromService:
          type: keyvalue
          name: asset-anchor-redis
          property: connectionString

      # ==== Database URL ====
      - fromGroup: asset-anchor-db-env

  - type: keyvalue
    name: asset-anchor-redis
    plan: free
    region: oregon
    ipAllowList: []

databases:
  - name: asset-anchor-db
    plan: standard
    region: oregon
    ipAllowList: []
    # Standard PostgreSQL database for production use
    # Adjust plan as needed based on scale requirements

envVarGroups:
  - name: asset-anchor-db-env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asset-anchor-db
          property: connectionString
