services:
  - type: web
    name: portfolio-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn -b 0.0.0.0:10000 src.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
    autoDeploy: true
    branch: main
    rootDir: backend
