route:
  receiver: dev-null
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - matchers: [severity="critical"]
    receiver: pagerduty
    continue: true
  - matchers: [severity=~"high|medium"]
    receiver: slack

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity=~"high|medium"]
    equal: ['alertname', 'service']

receivers:
  - name: dev-null
  - name: slack
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: ${SLACK_CHANNEL}
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
        send_resolved: true
  - name: pagerduty
    pagerduty_configs:
      - routing_key: ${PAGERDUTY_INTEGRATION_KEY}
        severity: "{{ if eq .CommonLabels.severity \"critical\" }}critical{{ else }}error{{ end }}"
        send_resolved: true

templates:
  - '/etc/alertmanager/templates/*.tmpl'
