global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    metrics_path: /api/metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["backend:5050"]

  - job_name: "postgres"
    static_configs:
      - targets: ["db:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
