apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 120s
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo
    
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    version: 1
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: "traceID=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: tempo
          urlDisplayLabel: "Open Trace"
    
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    version: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        mapTagNamesEnabled: true
        tags: ['service.name', 'service.namespace', 'job']
        mappedTags: [{ key: 'service.name', value: 'app' }]
        filterByTraceID: true
        filterBySpanID: false
    
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: default
      defaultRegion: us-east-1
    editable: true
