"""add_maintenance_type

Revision ID: 9a7c4d21e508
Revises: 8a6b5a055408
Create Date: 2025-08-07 16:35:45.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7c4d21e508'
down_revision = '8a6b5a055408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('maintenance_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_requests', 'maintenance_type')
    # ### end Alembic commands ###
