name: backend-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  be-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: pytest -q
