name: backend-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  be-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
...
        if: hashFiles('backend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: trivy-backend

      - name: Upload Trivy frontend scan results
        if: hashFiles('frontend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: trivy-frontend
