# .github/workflows/backend-ci.yml
name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install system deps (psycopg2)
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
      
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      
      - name: Run tests
        env:
          FLASK_ENV: test
          DATABASE_URL: sqlite:///test.db
          RATELIMIT_STORAGE_URI: memory://
          DISABLE_RATE_LIMIT: "true"
          SENTRY_DSN: ""
          STRIPE_SECRET_KEY: "sk_test_dummy"
          STRIPE_WEBHOOK_SECRET: "whsec_dummy"
        run: python -m pytest
      
      - name: Check if Dockerfile exists
        id: dockerfile_check
        run: |
          if [ -f Dockerfile ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Trivy vulnerability scanner
        if: steps.dockerfile_check.outputs.exists == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'project-name-backend:scan'
          format: 'sarif'
          output: 'trivy-backend-results.sarif'
      
      - name: Upload Trivy scan results
        if: steps.dockerfile_check.outputs.exists == 'true'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: trivy-backend
