name: backend-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  be-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (psycopg2)
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Show Python deps
        run: pip freeze

      - name: Run pytest with coverage
        env:
          FLASK_ENV: test
          DATABASE_URL: sqlite:///test.db
          RATELIMIT_STORAGE_URI: memory://
          DISABLE_RATE_LIMIT: "true"
          SENTRY_DSN: ""
          STRIPE_SECRET_KEY: "sk_test_dummy"
          STRIPE_WEBHOOK_SECRET: "whsec_dummy"
        run: python -m pytest

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.xml
...
        if: hashFiles('backend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: trivy-backend

      - name: Upload Trivy frontend scan results
        if: hashFiles('frontend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: trivy-frontend
