name: deploy
on:
  push:
    branches: [ main# Removed redundant code block
# Prevent simultaneous deploys
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Reuse the frontend and backend test jobs
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml

...
      - name: Upload Trivy backend scan results
        if: hashFiles('backend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: trivy-backend

      - name: Upload Trivy frontend scan results
        if: hashFiles('frontend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: trivy-frontend
