# .github/workflows/frontend-tests.yml

name: frontend-tests

on:
  push:
    branches: [ main ]
    paths: [ "frontend/**", ".github/workflows/frontend-tests.yml" ]
  pull_request:
    branches: [ main ]
    paths: [ "frontend/**", ".github/workflows/frontend-tests.yml" ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: frontend-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fe-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if placeholder code exists
        run: |
          echo "Scanning for placeholder patterns…"
          set -e
          patterns='(^|\s)\.\.\.($|\s)|PLACEHOLDER|TO_FILL|__FILL_ME__|FIXME!!!'
          if git grep -nE "$patterns" -- frontend ':!**/node_modules' ':!**/dist' ':!**/build' ; then
            echo "::error::Placeholder patterns found. Remove them before pushing."
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint (if script exists)
        run: |
          node -e "const p=require('./package.json'); process.exit(p.scripts?.lint?0:1)"
          npm run lint
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          # Prefer project script if it exists
          if npm run | grep -q 'test:ci'; then
            npm run test:ci
          else
            # Force CI + coverage even if package.json doesn't include it
            npm test -- --ci --coverage
          fi

      - name: Build application (sanity)
        run: npm run build --if-present

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
          if-no-files-found: ignore
