name: Performance Smoke Tests

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 3 * * 1'  # Run weekly on Mondays at 3am UTC

jobs:
  perf-smoke:
    name: Run Performance Smoke Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
...
        run: |
          k6 run -e API_URL=https://api-staging.assetanchor.io perf/k6/smoke.js
      
      - name: Run smoke test against production
        run: |
          k6 run -e API_URL=https://api.assetanchor.io perf/k6/smoke.js
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: k6-results
          path: |
            k6-summary-*.json
            k6-*.html
