name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    branches: [ main ]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/requirements.txt'
      - 'Pipfile'
      - 'Pipfile.lock'
  pull_request:
    branches: [ main ]
    paths:
...
          output: 'trivy-frontend-results.sarif'

      - name: Upload Trivy backend scan results
        if: hashFiles('backend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-backend-results.sarif'
          category: trivy-backend

      - name: Upload Trivy frontend scan results
        if: hashFiles('frontend/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-frontend-results.sarif'
          category: trivy-frontend
